import React from 'react';

const Content = () => {

  return (
    <>
      <div className='sidebar-detail'>
        <ul>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
          <li>テスト</li>
        </ul>
      </div>
    </>
  );
}

export default Content;
