# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test

  deploy-s3:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    # Allow write on id-token so we can use it to authenticate to AWS
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
        env:
          REACT_APP_API_STAGE: 'v1'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::584344484091:role/maps-takamatsu-fact-com-github-actions-deploy-v1
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://maps-takamatsu-fact-com-frontend-v1 \
            --delete \
            --cache-control "public,max-age=60" \

          aws cloudfront create-invalidation --distribution-id "EST3VP61MN1X3" --paths "/*"
